services:
  - type: web
    name: fake-job-detection-api
    runtime: docker
    plan: free
    region: oregon
    dockerContext: backend
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
